import type { Program, Plan, Testimonial, BlogPost, FAQItem } from './types'

export const SITE = {
  name: 'Coach Nati',
  tagline: 'Train With the Best. Anytime, Anywhere.',
  email: 'hello@coachnati.com',
  phone: '+1 (555) 012-3456',
  whatsapp: '+15550123456',
  address: 'Arena One, 12 Wellness Avenue, Addis Ababa',
  socials: {
    instagram: 'https://instagram.com',
    youtube: 'https://youtube.com',
    tiktok: 'https://tiktok.com',
    telegram: 'https://t.me',
    twitter: 'https://x.com',
  },
}

export const PLATFORM_STATS = [
  { value: 10, suffix: '+', label: 'Years Experience' },
  { value: 500, suffix: '+', label: 'Active Members' },
  { value: 50, suffix: '+', label: 'Programs' },
]

export const PLATFORM_WHY = [
  {
    icon: 'Globe',
    title: 'Pioneer a New Market',
    desc: 'Lead the digital fitness revolution. Access untapped potential with online training built for modern athletes.',
  },
  {
    icon: 'FileText',
    title: 'Create Digital Courses',
    desc: 'Transform your expertise into sellable assets — professional guides, programs, and online coaching packages.',
  },
  {
    icon: 'TrendingUp',
    title: 'Grow Your Audience',
    desc: 'We help you build a real, engaged following ready to invest in your programs and courses.',
  },
  {
    icon: 'Zap',
    title: 'Skip to Modern Systems',
    desc: 'Leapfrog outdated methods with the same tech and systems used by top global fitness professionals.',
  },
]

export const STATS = [
  { value: 500, suffix: '+', label: 'Clients' },
  { value: 10, suffix: '+', label: 'Years Coaching' },
  { value: 1000, suffix: '+', label: 'Workouts Created' },
  { value: 98, suffix: '%', label: 'Success Rate' },
]

export const TRUST_LOGOS = ['Strength Lab', 'FitHive', 'CoreStudio', 'PulseGym', 'VitaLife', 'IronWorks', 'Nordic Fit', 'Zenith Health']

export const SERVICES = [
  { icon: 'Dumbbell', title: 'Personal Training', desc: '1:1 in-person sessions engineered around your body, your schedule and your goals.' },
  { icon: 'MonitorPlay', title: 'Online Coaching', desc: 'Full remote coaching with daily support, video feedback and a personal app dashboard.' },
  { icon: 'Apple', title: 'Meal Plans', desc: 'Custom nutrition built on whole foods — flexible, sustainable and results driven.' },
  { icon: 'Activity', title: 'Fitness Assessment', desc: 'Deep body composition, movement and mobility analysis to build your baseline.' },
  { icon: 'HeartPulse', title: 'Lifestyle Coaching', desc: 'Sleep, stress and habit systems that make your transformation permanent.' },
  { icon: 'Zap', title: 'Strength Coaching', desc: 'Progressive strength programming for size, power and athletic performance.' },
  { icon: 'Flame', title: 'Weight Loss Coaching', desc: 'Science-backed fat loss protocols with weekly check-ins and accountability.' },
  { icon: 'BatteryCharging', title: 'Recovery Coaching', desc: 'Mobility, breathwork and recovery strategies to train harder for longer.' },
]

export const WHY_CHOOSE = [
  { icon: 'ClipboardList', title: 'Personal Workout Plans', desc: 'Programs written for your body, your equipment and your schedule.' },
  { icon: 'Salad', title: 'Nutrition Strategy', desc: 'Flexible macro-based nutrition built on foods you actually enjoy.' },
  { icon: 'ChartColumn', title: 'Progress Tracking', desc: 'Body metrics, measurements and photos tracked automatically.' },
  { icon: 'MessageSquare', title: 'Weekly Check-ins', desc: 'Data-driven check-ins that keep you accountable and on trajectory.' },
  { icon: 'Video', title: 'Exercise Guidance', desc: 'Video tutorials and form reviews with personalized feedback.' },
  { icon: 'HeartPulse', title: 'Lifestyle Coaching', desc: 'Sleep, stress and habit systems that make your transformation permanent.' },
]

export const PROGRAMS: Program[] = [
  {
    id: 'p_weightloss',
    slug: 'weight-loss',
    name: 'Weight Loss',
    tagline: 'Burn fat without burning out',
    description: 'A calorie-smart fat loss system combining strength training, cardio and nutrition that melts fat while keeping muscle.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Beginner',
    goal: 'Weight Loss',
    price: 6000,
    plan: 'monthly',
    icon: 'Flame',
    color: '#F59E0B',
    benefits: ['Lose 8–15 kg', 'Keep muscle', 'Learn to eat for life', 'Weekly weigh-ins'],
    features: ['Personalized plan', 'Daily support', 'Progress tracking', 'Meal plan'],
  },
  {
    id: 'p_muscle',
    slug: 'muscle-gain',
    name: 'Muscle Gain',
    tagline: 'Add lean mass, fast',
    description: 'Progressive overload programming with precise nutrition to build dense, aesthetic muscle in the shortest time possible.',
    duration: '16 weeks',
    weeks: 16,
    level: 'Intermediate',
    goal: 'Muscle Gain',
    price: 7200,
    plan: 'monthly',
    popular: true,
    icon: 'Dumbbell',
    color: '#E11D48',
    benefits: ['Gain 5–9 kg muscle', 'Strength PRs weekly', 'Advanced splits', 'Form coaching'],
    features: ['Personalized plan', 'Video tutorials', 'Nutrition coaching', 'Progress tracking'],
  },
  {
    id: 'p_strength',
    slug: 'strength-training',
    name: 'Strength Training',
    tagline: 'Get brutally strong',
    description: 'Powerlifting and strength focused programming built around the big lifts with technique coaching at the core.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Advanced',
    goal: 'Strength Training',
    price: 6400,
    plan: 'monthly',
    icon: 'Zap',
    color: '#F59E0B',
    benefits: ['Add 25kg+ to total', 'Perfect technique', 'Meet PR targets'],
    features: ['Strength plan', 'Form reviews', 'Accessory work', 'Progress tracking'],
  },
  {
    id: 'p_fatburn',
    slug: 'fat-burning',
    name: 'Fat Burning',
    tagline: 'Melt stubborn fat fast',
    description: 'High-intensity conditioning and metabolic circuits that torch calories and keep your metabolism firing long after training.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Intermediate',
    goal: 'Fat Burning',
    price: 6000,
    plan: 'monthly',
    icon: 'Flame',
    color: '#F59E0B',
    benefits: ['Drop body fat %', 'Boost metabolism', 'High-energy sessions'],
    features: ['Fat loss plan', 'Nutrition guidance', 'Progress tracking'],
  },
  {
    id: 'p_online',
    slug: 'online-coaching',
    name: 'Online Coaching',
    tagline: 'Train anywhere, coach everywhere',
    description: 'Full remote coaching with a personal app dashboard, video feedback, weekly check-ins and daily messaging support.',
    duration: '12 weeks',
    weeks: 12,
    level: 'All levels',
    goal: 'Overall Fitness',
    price: 8000,
    plan: 'monthly',
    icon: 'MonitorPlay',
    color: '#22C55E',
    benefits: ['Coach from anywhere', 'Daily support', 'Video form reviews'],
    features: ['App dashboard', 'Daily messaging', 'Weekly check-ins'],
  },
  {
    id: 'p_personal',
    slug: 'personal-training',
    name: 'Personal Training',
    tagline: '1:1 sessions, in person',
    description: 'Hands-on 1:1 in-person training with Coach Nati — every rep coached, every meal planned, every week accounted for.',
    duration: 'Flexible',
    weeks: 12,
    level: 'All levels',
    goal: 'Overall Fitness',
    price: 12000,
    plan: 'monthly',
    icon: 'Dumbbell',
    color: '#E11D48',
    benefits: ['1:1 in-person', 'Live form coaching', 'Full accountability'],
    features: ['1:1 sessions', 'Meal planning', 'Weekly check-ins'],
  },
  {
    id: 'p_recomp',
    slug: 'body-recomposition',
    name: 'Body Recomposition',
    tagline: 'Lose fat, build muscle — together',
    description: 'The holy grail: simultaneous fat loss and muscle gain through precise periodization and nutritional cycling.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Intermediate',
    goal: 'Body Recomposition',
    price: 8000,
    plan: 'monthly',
    icon: 'RefreshCcw',
    color: '#22C55E',
    benefits: ['Recomp your physique', 'Visible in 30 days', 'Tighter, stronger body'],
    features: ['Personalized plan', 'Body fat tracking', 'Meal plan', 'Weekly check-ins'],
  },
  {
    id: 'p_women',
    slug: 'womens-fitness',
    name: "Women's Fitness",
    tagline: 'Strong, confident, unstoppable',
    description: 'A program designed for women to build strength, confidence and a physique they love — with zero intimidation.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Beginner',
    goal: 'Mixed',
    price: 6000,
    plan: 'monthly',
    icon: 'Flower',
    color: '#EC4899',
    benefits: ['Tone & strengthen', 'Build confidence', 'Community support'],
    features: ['Personalized plan', 'Nutrition guidance', 'Weekly check-ins'],
  },
  {
    id: 'p_men',
    slug: 'mens-fitness',
    name: "Men's Fitness",
    tagline: 'Look strong, feel unstoppable',
    description: 'Lean, athletic conditioning for men — build the classic V-taper physique and real functional strength.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Beginner',
    goal: 'Mixed',
    price: 6000,
    plan: 'monthly',
    icon: 'Shield',
    color: '#3B82F6',
    benefits: ['Build the V-taper', 'Boost testosterone', 'Stronger core'],
    features: ['Personalized plan', 'Nutrition coaching', 'Progress tracking'],
  },
  {
    id: 'p_home',
    slug: 'home-workout',
    name: 'Home Workout',
    tagline: 'No gym? No problem',
    description: 'Train at home with bodyweight or dumbbells only. Same intensity, same results — zero commute.',
    duration: '8 weeks',
    weeks: 8,
    level: 'Beginner',
    goal: 'Mixed',
    price: 4000,
    plan: 'monthly',
    icon: 'House',
    color: '#22C55E',
    benefits: ['No equipment needed', 'Short effective sessions', 'Guided video demos'],
    features: ['Home plan', 'Video tutorials', 'Daily support'],
  },
  {
    id: 'p_athlete',
    slug: 'athlete-program',
    name: 'Athlete Program',
    tagline: 'Compete at your peak',
    description: 'Sport-specific conditioning, speed, power and recovery programming for competitive athletes.',
    duration: '12 weeks',
    weeks: 12,
    level: 'Advanced',
    goal: 'Mixed',
    price: 9200,
    plan: 'monthly',
    icon: 'Trophy',
    color: '#F59E0B',
    benefits: ['Sport-specific power', 'Injury prevention', 'Peak performance'],
    features: ['Athlete plan', 'Recovery coaching', 'Video feedback'],
  },
  {
    id: 'p_beginner',
    slug: 'beginner-program',
    name: 'Beginner Program',
    tagline: 'Start strong, start right',
    description: 'Your first 90 days done right — build habits, learn the lifts and see your first major transformation.',
    duration: '8 weeks',
    weeks: 8,
    level: 'Beginner',
    goal: 'Overall Fitness',
    price: 4000,
    plan: 'monthly',
    icon: 'Sprout',
    color: '#E11D48',
    benefits: ['Learn correct form', 'Build habits', 'First transformation'],
    features: ['Beginner plan', 'Form tutorials', 'Daily support'],
  },
]

export const PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    tagline: 'For building momentum',
    monthly: 3200,
    quarterly: 8500,
    yearly: 31600,
    features: [
      'Pre-built workout library',
      'Nutrition template',
      'Weekly progress check',
      'Email support',
      'BMI & macro tools',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    tagline: 'For serious transformation',
    monthly: 6000,
    quarterly: 16100,
    yearly: 59600,
    popular: true,
    highlights: ['Most popular'],
    features: [
      'Fully personalized program',
      'Custom meal plan',
      'Weekly video check-ins',
      'Daily WhatsApp support',
      'Video form reviews',
      'Progress dashboard',
      'Access to app dashboard',
    ],
  },
  {
    id: 'elite',
    name: 'Elite',
    tagline: 'For complete 1:1 dedication',
    monthly: 12000,
    quarterly: 32300,
    yearly: 119600,
    features: [
      'Everything in Pro',
      '3× weekly live 1:1 calls',
      '24/7 priority messaging',
      'In-person sessions (city)',
      'Supplement protocols',
      'Recovery & lifestyle coaching',
      'Quarterly photo shoots',
    ],
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah M.',
    role: 'Lost 14 kg in 6 months',
    quote: 'Coach Nati rebuilt my relationship with food and training. I went from dreading workouts to craving them. The daily support is unreal.',
    rating: 5,
    result: '-14 kg',
    program: 'Weight Loss',
    before: '82kg',
    after: '68kg',
    months: 6,
  },
  {
    id: 't2',
    name: 'David K.',
    role: 'Gained 8 kg of muscle',
    quote: 'I had been training for years with average results. In four months with Nati I added more muscle than in my previous four years.',
    rating: 5,
    result: '+8 kg muscle',
    program: 'Muscle Gain',
    before: '72kg',
    after: '80kg',
    months: 4,
  },
  {
    id: 't3',
    name: 'Hanna T.',
    role: 'Post-pregnancy comeback',
    quote: 'As a new mom I had zero time. Nati built me a 35-minute home program that transformed my strength and confidence.',
    rating: 5,
    result: '-11% body fat',
    program: "Women's Fitness",
    before: '31%',
    after: '20%',
    months: 7,
  },
  {
    id: 't4',
    name: 'Michael R.',
    role: 'Stronger than ever at 45',
    quote: 'The strength programming is elite. I hit a 160kg deadlift at 45, injury-free, and my posture has completely changed.',
    rating: 5,
    result: '+40kg deadlift',
    program: 'Strength Training',
    before: '120kg',
    after: '160kg',
    months: 5,
  },
  {
    id: 't5',
    name: 'Lily A.',
    role: 'Home workout convert',
    quote: 'I thought I needed a gym membership to see results. Nati proved me wrong — my home program gave me the best shape of my life.',
    rating: 5,
    result: 'Fit at home',
    program: 'Home Workout',
    before: 'Sedentary',
    after: 'Active',
    months: 3,
  },
  {
    id: 't6',
    name: 'Yonas B.',
    role: 'Recomp — same weight, new body',
    quote: 'The recomposition program is genuinely a cheat code. My weight barely moved but my waist dropped 12cm.',
    rating: 5,
    result: '-12cm waist',
    program: 'Body Recomposition',
    before: '98cm',
    after: '86cm',
    months: 4,
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    slug: 'protein-masterclass',
    title: 'The Protein Masterclass: How Much You Really Need to Build Muscle',
    excerpt: 'Stop guessing. The exact protein numbers for muscle gain, fat loss and performance — and the best sources to hit them.',
    category: 'Nutrition',
    readMinutes: 6,
    author: 'Coach Nati',
    date: '2026-07-28',
    cover: 'nutrition',
    content: [
      'Protein is the single most important nutrient for anyone serious about their body. It is the building block of muscle, the most satiating macro, and the key to retaining muscle while losing fat.',
      'The scientific consensus points to 1.6–2.2g of protein per kg of bodyweight per day for active individuals. Beginners pushing hard should aim for the upper end, while maintenance is comfortable at the lower end.',
      'Quality sources include whole eggs, lean meat, fish, Greek yogurt, cottage cheese and plant options like lentils, tofu and tempeh. Spread your intake across 3–5 meals for optimal muscle protein synthesis.',
      'Supplement with whey or plant protein only to fill the gap — real food first, always. And remember: protein without progressive training is wasted on building muscle.',
    ],
  },
  {
    id: 'b2',
    slug: 'fat-loss-no-cardio',
    title: 'How to Lose Fat Without Obsessing Over Cardio',
    excerpt: 'Fat loss is won in the kitchen and the weight room. Here is the smarter way to shed fat and keep it off for good.',
    category: 'Fitness',
    readMinutes: 5,
    author: 'Coach Nati',
    date: '2026-07-20',
    cover: 'fitness',
    content: [
      'Cardio is not the enemy — but it is also not the answer. Fat loss happens when you consistently eat in a modest calorie deficit while giving your body a reason to hold onto muscle.',
      'The resistance training bias: lifting weights while dieting signals your body to preserve muscle. Muscle is your metabolic engine, so protecting it keeps your metabolism high.',
      'A sustainable deficit of 300–500 calories per day beats crash dieting every time. Slow and steady means the weight stays off and your hormones stay happy.',
      'When you do cardio, prefer daily steps and low-intensity work like walking. Save high-intensity intervals for when you are leaner and want to preserve muscle.',
    ],
  },
  {
    id: 'b3',
    slug: 'training-split-guide',
    title: 'The Complete Guide to Training Splits (and Which Is Right for You)',
    excerpt: 'Full body, upper/lower, push/pull/legs — we break down every popular split and exactly who each one is for.',
    category: 'Workout',
    readMinutes: 8,
    author: 'Coach Nati',
    date: '2026-07-12',
    cover: 'workout',
    content: [
      'Your training split is simply how you organize your weekly workouts. The best split is the one you can sustain consistently for months — not the one that looks coolest on paper.',
      'Full body (2–3 days) is perfect for beginners and time-poor lifters. Upper/Lower (4 days) is the best all-rounder for most people.',
      'Push/Pull/Legs (6 days) suits advanced lifters with high recovery capacity. Arnold splits and bro splits work only if you are already experienced and eat perfectly.',
      'Whatever you choose, progression is king. Add weight or reps over time and your body will adapt by growing stronger and more muscular.',
    ],
  },
  {
    id: 'b4',
    slug: 'sleep-is-the-anabolic',
    title: 'Sleep Is the Most Anabolic Thing You Do (And You Are Not Doing Enough)',
    excerpt: 'Recovery, hormones, fat loss and muscle growth — all wired to one habit you are probably skipping. Here is why.',
    category: 'Lifestyle',
    readMinutes: 4,
    author: 'Coach Nati',
    date: '2026-07-05',
    cover: 'lifestyle',
    content: [
      'Sleep is where the magic happens. Deep sleep is when your body releases the majority of its growth hormone — the natural signal to build muscle and burn fat.',
      'Sleeping under 6 hours raises cortisol and ghrelin, making you hungrier, weaker and more prone to storing fat around your middle.',
      'Aim for 7–9 quality hours. Protect your last hour before bed: dim the lights, drop screens, keep the room cool and dark.',
      'Treat sleep like a training session. If you are serious about results, recovering is as important as the workout itself.',
    ],
  },
  {
    id: 'b5',
    slug: 'water-and-hydration',
    title: 'Hydration: The Free Performance Enhancer You Are Ignoring',
    excerpt: 'Even 2% dehydration tanks your performance and focus. Your daily water targets and the best times to drink.',
    category: 'Nutrition',
    readMinutes: 4,
    author: 'Coach Nati',
    date: '2026-06-28',
    cover: 'lifestyle',
    content: [
      'Water regulates your temperature, transports nutrients, and is required for every metabolic reaction in your body — including muscle contraction.',
      'Studies show that 2% dehydration can reduce strength performance by up to 5% and mental focus significantly. In a gym, that is missed reps and injuries.',
      'A good baseline is 30–40ml per kg of bodyweight, plus extra around workouts. Start the day with a large glass and sip steadily rather than chugging.',
      'Add electrolytes when you sweat heavily. Salt, potassium and magnesium keep your pumps full and your cramps away.',
    ],
  },
  {
    id: 'b6',
    slug: 'beginner-gym-guide',
    title: 'Your First 30 Days in the Gym: The Complete Beginner Survival Guide',
    excerpt: 'Everything a total beginner needs: what to do, what to eat and how to avoid the classic first-month mistakes.',
    category: 'Workout',
    readMinutes: 7,
    author: 'Coach Nati',
    date: '2026-06-20',
    cover: 'workout',
    content: [
      'Your first month is about learning, not grinding. Master a handful of fundamental movements with light weight and perfect form before adding load.',
      'Start with a simple full-body plan, 3 days per week. Squat pattern, hinge pattern, push and pull — that is genuinely enough to build your base.',
      'Track your lifts from day one. The numbers are your roadmap: if you are adding reps or weight each week, you are winning.',
      'Ignore the bro science at the water cooler. Consistency, progressive overload and protein are the only three things you truly need.',
    ],
  },
]

export const FAQS: FAQItem[] = [
  {
    id: 'f1',
    question: 'How quickly will I see results?',
    answer:
      'Most clients notice changes in energy and strength within 2–3 weeks, visible body changes in 4–6 weeks, and significant transformations within 12 weeks. Progress depends on consistency and following the plan.',
    category: 'General',
  },
  {
    id: 'f2',
    question: 'I am a complete beginner. Is this right for me?',
    answer:
      'Absolutely. Around 60% of my clients start as total beginners. Every program is built around your current level, and you will be coached on form and technique from day one.',
    category: 'General',
  },
  {
    id: 'f3',
    question: 'Do I need a gym membership?',
    answer:
      'No. I offer both gym-based and home programs. Many clients train with zero equipment or just a pair of dumbbells and still get elite results.',
    category: 'General',
  },
  {
    id: 'f4',
    question: 'How does online coaching actually work?',
    answer:
      'After onboarding, you get access to your personal dashboard with your workouts, meal plan, progress tracking and direct messaging. I review your videos, track your numbers and adjust the plan weekly.',
    category: 'Coaching',
  },
  {
    id: 'f5',
    question: 'What if I have injuries or medical conditions?',
    answer:
      'During your health assessment we map out any conditions. I design your program around them, and where needed I work with your physician or physiotherapist.',
    category: 'Coaching',
  },
  {
    id: 'f6',
    question: 'Can I change my program later?',
    answer:
      'Yes. Your plan is reviewed every month. If your goals shift — or a program is not the right fit — we adjust your programming without extra cost.',
    category: 'Billing',
  },
  {
    id: 'f7',
    question: 'Do you offer refunds?',
    answer:
      'Yes — a 14-day money-back guarantee on your first month. If you are not satisfied, tell me and I will refund you in full. No questions asked.',
    category: 'Billing',
  },
  {
    id: 'f8',
    question: 'What equipment do I need for a home program?',
    answer:
      'My home programs scale from bodyweight-only to dumbbell-based. I recommend a set of adjustable dumbbells and a mat as the baseline for best results.',
    category: 'General',
  },
]

export const PROCESS_STEPS = [
  { title: 'Fitness Assessment', desc: 'Body composition, movement screening and a full health review to build your baseline.' },
  { title: 'Goal Planning', desc: 'We define your target weight, body composition and a realistic timeline.' },
  { title: 'Custom Program', desc: 'Your personalized training and nutrition plan, built around your equipment and schedule.' },
  { title: 'Weekly Coaching', desc: 'Check-ins, measurements, progress photos and plan adjustments every single week.' },
  { title: 'Transformation', desc: 'Your new body, new habits and the confidence to keep it forever.' },
]

export const GALLERY_ITEMS = [
  { img: 'gym-1', tag: 'Strength', span: 'tall' },
  { img: 'gym-2', tag: 'Training', span: 'wide' },
  { img: 'gym-3', tag: 'Lifestyle', span: 'normal' },
  { img: 'gym-4', tag: 'Outdoor', span: 'tall' },
  { img: 'gym-5', tag: 'Mobility', span: 'normal' },
  { img: 'gym-6', tag: 'Nutrition', span: 'wide' },
  { img: 'gym-7', tag: 'Conditioning', span: 'normal' },
  { img: 'gym-8', tag: 'Community', span: 'tall' },
]

export const NUTRITION_TIPS = [
  { icon: 'Apple', title: 'Eat Protein First', desc: 'Anchor every meal around a palm-sized protein source. It builds muscle and keeps you full.' },
  { icon: 'Droplets', title: 'Hydrate Daily', desc: 'Aim for 30–40ml of water per kg of bodyweight, with electrolytes around training.' },
  { icon: 'Leaf', title: '80/20 Rule', desc: 'Keep 80% of your intake clean and leave 20% for foods you love. Sustainability wins.' },
  { icon: 'Sun', title: 'Sleep & Recover', desc: '7–9 hours of sleep is the most anabolic habit you can adopt. Recovery is growth.' },
]

export const MEAL_IDEAS = [
  { name: 'Protein Oats', kcal: 420, p: 32, c: 52, f: 11, emoji: '🥣' },
  { name: 'Grilled Chicken Bowl', kcal: 540, p: 48, c: 42, f: 18, emoji: '🍗' },
  { name: 'Salmon & Quinoa', kcal: 510, p: 40, c: 45, f: 16, emoji: '🐟' },
  { name: 'Egg White Omelette', kcal: 330, p: 30, c: 12, f: 18, emoji: '🍳' },
  { name: 'Greek Yogurt Parfait', kcal: 290, p: 26, c: 34, f: 6, emoji: '🍓' },
  { name: 'Beef & Sweet Potato', kcal: 560, p: 46, c: 55, f: 17, emoji: '🥩' },
]

export const ACHIEVEMENTS = [
  { icon: 'Dumbbell', title: 'Certified Coach', org: 'NSCA — Certified Strength & Conditioning' },
  { icon: 'Apple', title: 'Nutrition Expert', org: 'Precision Nutrition L2' },
  { icon: 'HeartPulse', title: 'Transformation Coach', org: '1,000+ lives transformed since 2016' },
  { icon: 'MonitorPlay', title: 'Fitness Mentor', org: 'Habit & behavior-change certified' },
]
